### ISSUE TITLE
Formatting not working for the docs site

### ISSUE THREAD

**Issue by josephxtian** [HACManchester/documentation#117]
It looks like the markdown i have written for https://github.com/HACManchester/documentation/blob/master/docs/Membership/Rules.md

has lost the links and lost the bullet point formatting when it gets uploaded to the website's docs system. Does anyone know why?
https://docs.hacman.org.uk/Membership/Rules/
![image](https://github.com/user-attachments/assets/3b44c88c-b977-45c6-b904-966a6ee5a150)

**Comment by Hecatron** [comment]
You need a newline so instead of this
```
When you visit, try to set aside 10-15 minutes before you leave to do some of the quick tasks that keep the space safe and usable for everyone. These include:
* Taking out the bins
* Sweeping the floors
```

It needs to be this
```
When you visit, try to set aside 10-15 minutes before you leave to do some of the quick tasks that keep the space safe and usable for everyone. These include:

* Taking out the bins
* Sweeping the floors
```

Also Markdown links sometimes are resolved automatically, but not always
In theory links should look like this `[Duck Duck Go](https://duckduckgo.com)`

I'll have a look and add some fixes

**Comment by Hecatron** [comment]
Another trick to force a newline at the end of a sentence is to add a double space.

I've now merged in some spacing changes, put the items under Prohibited Storage Items as bullet points. but no changes other than spacing / formatting.
